sudo: required
dist: trusty
os: linux
language: generic

env:
  - EMULATOR_VERSION=18 TARGET_VERSION=28 ABI="google_apis;armeabi-v7a" ANDROID_BUILD_TOOLS_VERSION=28.0.3 ADB_INSTALL_TIMEOUT=20 QEMU_AUDIO_DRV=none

before_install:
  - export ANDROID_HOME=~/android-sdk-linux
  - wget -q "https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip" -O android-sdk-tools.zip
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  - mkdir -p ~/.android
  - touch ~/.android/repositories.cfg
  - yes | sdkmanager --licenses
  - sdkmanager "emulator" "tools" "platform-tools" > /dev/null
  - sdkmanager --list | head -15
  - sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION" "platforms;android-$TARGET_VERSION" > /dev/null
  - sdkmanager "system-images;android-$EMULATOR_VERSION;$ABI" > /dev/null
  - sdkmanager --list | head -15
  - yes | sdkmanager "cmake;3.10.2.4988404"
  - wget https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip
  - unzip android-ndk-r18b-linux-x86_64.zip -d $HOME > /dev/null
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r18b
  - export PATH=$PATH:$ANDROID_NDK_HOME
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_VERSION;$ABI"

script:
  - cd android
  - ./gradlew assembleDebugAndroidTest -PdisablePreDex --continue --stacktrace
  - $ANDROID_HOME/emulator/emulator -avd test -no-window &
  - bash android-wait-for-emulator
  - adb shell input keyevent 82
  - ./gradlew connectedDebugAndroidTest -PdisablePreDex --continue --stacktrace
# deploy:
#   provider: releases
#   file: TravisExample.apk
#   skip_cleanup: true
#   on:
#     repo: rabee/TravisCiTest
#     tags: true
#     jdk: oraclejdk8
#   api_key:
#     secure: XfRzqK5WI+SUjUGZK40EjPmcqswp+63GJO7atQ8oHqIhR1i/usQt8E0mS0OjVpjfm8/0kDL+NMo0li64ct362h4jzHgGmwuoNfJWQSZBb1/UUZE7Dh21wYUb4DQ+KuezuZ+Fpy/PPHaVXbeQGi3wjoU1ybi5hAC78ok4q799McWWpj4ewp7Lo/Np3f05E5M+o1uJCEFn9A1i1bIcPSYDYtDJ9uM8HIwDBID0D9oOXd5ElGlNCGFoL/0yCqaj3bf3qauunC1rnTJ98hwjvEpwFNjkWu/qTkg6YF0cKKCjsjMzeh6cx+8Y+AHqzlQHe3brnVzvt4hP/tmX3OZzhMutoGPHI9dv61JbBmGBNqwo3s5Grln7wOQPz3sm7Oqk1g1GMVnTC9LuHqoV0Ala8VgbGJbGl7WlrDTAvwZetO5+DVD4xRWPOn5FBzpO3wSJFwESJgSp4KHvBwyQQbLSaNpKlZHevhiiuYGQ9dncg+sswEwmEaB1jAD+RRTCqp+dAgz3CKudeCG2CQJ1hzFeG/IskCfU0i0etK4cdP/LRABlvNj2P0fMfZ4fL1k8qTdysuLW8cNXZvGuQmoBypehUfaJ292ak+TMnsGZqpb7GOquTXWdIEyk0EVKqMe/HlWfVjPsJtmgYQlCFg/rgYRbNoBG890Y6k7GBFGi+xjNREnWNIA=